### ISSUE TITLE
Thermal Run-Away Error when raising Target Temperature Manually

### ISSUE THREAD

**Issue by Jojo-Madman** [andrivet/ADVi3pp#104] opened 2018-04-21 21:31 UTC
### Bug Report
- Description:
1. Started a print from SD card, and during the print decided to raise the temperature slightly (10C) to improve filament flow and adhesion to previous layer. The temperature of HotEnd was raised 10C manually by using the "Print Settings" override screen. Hotend started to rise slowly, then triggered Thermal Run-Away error and shut down print.
Tested printer after error and thermistor functions properly, and is not faulty.

2. Also test in thermal runaway error has formating error with text over text (see attached photo)

![20180421_150620](https://user-images.githubusercontent.com/36554741/39088952-d6f6bab4-4589-11e8-9659-7086a821bf47.jpg)

- Expected behaviour:
Able to adjust the temperature of hotend during a print without any thermal runaway error or system shutdown
 
- Actual behaviour:
Adjusting the temperature of the hotend during a print, triggers a thermal runaway error

- Steps to reproduce:
  - Start a print from SD card
  - Once print has started past the initial layer, and has started printing object, select Gear Symbol to get to Print Settings
  - Raise Hotend temperature by 10C
  - Select checkmark symbol to accept change
  - Hotend starts to rise in temperature and shortly afterwards triggers thermal runaway shutdown

**Comment by andrivet** [comment] 2018-05-06 13:14
The error is probably triggered because your heating is too slow. I tried to reproduce this behaviour (point 1) several times, but I am not able to. In all my tests, the temperature is rising normally and I get no error. Maybe, your PID settings are wrong (have you done a PID tuning?).

So for the moment, I close this issue. Feel free to reopen it if you still have problems. But please, **give enough information**. I am loosing too much time (i.e. 2 hours) trying to reproduce something without, for example, your extruding temperature (yes you raise by 10C, but from which temperature?)

**Closed as completed by andrivet** 2018-05-06 13:14 UTC
Labels: not confirmed
