### ISSUE TITLE
[Bug] manual move acts as though the nozzle is always in the x home position

### ISSUE THREAD

**Issue by ewortzman** [andrivet/ADVi3pp#122] opened 2018-05-14 22:23 UTC
------------------------------------------------------------
### Bug Report
- Description: manually moving the nozzle always acts as though the nozzle is in the x home position
- Expected behaviour: when opening the move menu, if the nozzle is not in the x home position, i should be able to move left until the x endstop is reached, or press the x-home button to move all the way to the home position
- Actual behaviour: when I initially open the move menu, if I attempt to move left, nothing happens, and if I press x-home, it acts as though the endstop were activated, when it is not (i.e. moving left briefly, then back right as though it triggered the endstop, then back left again, then stopping). If I press the "disable motors" button, _then_ I can move along the x axis as expected.
- Steps to reproduce:
  - with the nozzle in the middle of the x axis, go to the manual move menu
  - attempt to move the nozzle left, nothing will happen. 
  - press x-home, the nozzle will act as though it is already in the x home position
  - press disable motors in the top right of the screen
  - repeat steps 2 and 3, and it will behave as expected

**Comment by andrivet** [comment] 2018-05-14 22:24
Which version do you use?

**Comment by andrivet** [comment] 2018-05-14 22:26
Probably duplicate of #15

**Closed as completed by andrivet** 2018-05-14 22:26 UTC
Labels: duplicate

**Comment by ewortzman** [comment] 2018-05-14 22:36
I'm using version 3.0 beta 2 right now. I intend to update to beta 3 some time this week.
