### ISSUE TITLE
Is there a way to save the ESteps? It resets back to 114.1 after I turn it off. 

### ISSUE THREAD

**Issue by rippledabs** [andrivet/ADVi3pp#11] opened 2017-10-26 05:20 UTC
Thank you for submitting your feedback to the ADVi3++ project.
Please use one of the templates below to fill out this box.

------------------------------------------------------------
### Feature Request
Please put [FR] in the issue title: `[FR] Add-on that goes 'ping'`

------------------------------------------------------------
### Bug Report
- Description: ---
- Expected behaviour: ---
- Actual behaviour: ---
- Steps to reproduce:
  - Do this
  - Do that

------------------------------------------------------------
### Bug Report Tips
- Format text with: **bold**, _italic_, `code`.
- Format C++ with three backticks, plus "cpp":
```cpp
void my_function(bool do_it) {
  // Hold this spot
}
```

**Comment by andrivet** [comment] 2017-10-26 09:33
Duplicate of #9

**Closed as completed by andrivet** 2017-10-26 09:33 UTC
