### ISSUE TITLE
[FR] On print pause move bed to home

### ISSUE THREAD

**Issue by argus357** [andrivet/ADVi3pp#90] opened 2018-04-10 22:59 UTC
When a print is paused could the bed be retracted to the the home position so heat from the nozzle does not damage the print? Bed then returns to last position when the print is resumed.
Beta 2 is a fantastic improvement over the stock firmware, thank you for your efforts.

**Comment by andrivet** [comment] 2018-04-11 14:01
Duplicate of #8 and #18

**Closed as completed by andrivet** 2018-04-11 14:01 UTC
Labels: duplicate
