### ISSUE TITLE
BUG: Beta 2 - Homing X sometimes does not work.

### ISSUE THREAD

**Issue by wescrockett** [andrivet/ADVi3pp#92] opened 2018-04-12 00:02 UTC
When working with Beta 2, I have found that, at times, the X axis will not home... whether through octoprint or the printer control display.

It seems to happen when you have manually moved the head at some point when it previously thought it was already homed.

I will try to iron out the reproduction steps, but it seems to think it is already homed.

**Comment by andrivet** [comment] 2018-04-12 06:25
Duplicate of #15

**Closed as completed by andrivet** 2018-04-12 06:25 UTC
Labels: duplicate

**Comment by wescrockett** [comment] 2018-04-12 13:55
Ah. sorry. thanks!
