### ISSUE TITLE
Reproducible screen stucked

### ISSUE THREAD

**Issue by timangus** [andrivet/ADVi3pp#55] opened 2018-02-06 22:50 UTC
- Description: Crash to white screen with no ability to control the printer.
- Expected behaviour: Return to the main menu from the print temp monitor screen
- Actual behaviour: White screen, no control of printer.
- Steps to reproduce:
  - With **no SD card inserted**, power on the printer
  - Press Print
  - Press Controls (without waiting for the Print screen to appear)
  - The Print screen appears (and not the Controls one)
  - Press back
  - White screen

**Comment by andrivet** [comment] 2018-02-06 22:58
I am not able to reproduce the behavior: if I power on the printer and there is no SD card inserted, when I press Print, I have the Temperature screen without controls.

The only way I found to reproduce something close is to insert the SD card start a Print, remove the SD card, etc.

**Comment by timangus** [comment] 2018-02-07 00:04
Hmm, that's odd. Something weird about my printer/setup/install? https://youtu.be/OvLxc6Qw6ZI

**Comment by andrivet** [comment] 2018-02-07 00:08
I did not understand that you press the two icons so quicly. With the video, it is clear. It is a bug in ADVi3++

**Comment by timangus** [comment] 2018-02-07 00:12
Ah cool. Sorry, probably should have made that clear.

**Comment by andrivet** [comment] 2018-04-08 13:50
Fixed in Beta 2

**Closed as completed by andrivet** 2018-04-08 13:50 UTC
Labels: bug
