### ISSUE TITLE
Semi-auto bed leveling

### ISSUE THREAD

**Issue by gonzob** [andrivet/ADVi3pp#250] opened 2021-04-08 21:22 UTC
This is a feature request.

I don’t have the auto bed leveling feature, and I wasn’t planning on installing it, however it occurred to me that the “grid” that the auto-leveling creates could be done manually. The idea would be that:

*  you first generally level the bed using the adjusting screws and a sheet of paper
* you put the system into “semi-auto-leveling” mode
* you are then guided through a series of extruder grid points where you use the up/down controls to fine tune the extruder z-position, again using the sheet of paper
* the extruder z-position at these points is saved (and remembered) as the z-axis auto-level grid.

Gonzo

**Comment by andrivet** [comment] 2021-04-08 21:31
What is the advantage of doing this compared to a regular manual leveling?

**Comment by gonzob** [comment] 2021-04-09 16:36
The advantage is the same as you get with the auto bed sensing - the ability to compensate for slight variations in the surface of the bed. It would be achieved by manually "sensing" the height and creating the same map that the auto sensor makes. It won't be as accurate, but it would be better than using manual leveling and then assuming the bed is perfectly level.

**Comment by ryamoo** [comment] 2021-04-09 16:40
> The advantage is the same as you get with the auto bed sensing - the ability to compensate for slight variations in the surface of the bed. It would be achieved by manually "sensing" the height and creating the same map that the auto sensor makes. It won't be as accurate, but it would be better than using manual leveling and then assuming the bed is perfectly level.

@gonzob It's a feature that already exists on Marlin - I think its part of UBL (unified bed levelling).
You could technically download Advi3++ source and enable it yourself, then compile and flash and do the bed levelling stuff from a terminal (printer face or octoprint for example), you just wouldn't have it on the UI.

**Comment by andrivet** [comment] 2021-04-11 11:58
> The advantage is the same as you get with the auto bed sensing - the ability to compensate for slight variations in the surface of the bed. It would be achieved by manually "sensing" the height and creating the same map that the auto sensor makes. It won't be as accurate, but it would be better than using manual leveling and then assuming the bed is perfectly level.

OK, get it.

**Comment by andrivet** [comment] 2021-10-04 12:08
Looks like a duplicate of #59 so closing in favor of it.

**Closed as completed by andrivet** 2021-10-04 12:08 UTC
Labels: enhancement
