### ISSUE TITLE
Enable Manual Mesh Bed Leveling

### ISSUE THREAD

**Issue by jallen810** [andrivet/ADVi3pp#237] opened 2020-03-21 22:34 UTC
Andrivet,

I just installed the latest revision on my MPMaker Select. One feature I would very much like to see is the option to enable manual mesh bed leveling. I saw some other people talking about this but have not found the raw files to try and accomplish this myself and don't see anything other than the basic screw nut leveling in the existing firmware. 
1.) I would very much like to see this added to the "Tuning" menu in your next firmware with the option to customize the number of points to probe in the X & Y AND allow an offset for binder clips
2.) Can you perhaps point me in the direction the source code for your firmware and basic instructions? Note: I have watched Teaching Tech's [video](https://www.youtube.com/watch?v=lHLMkjnuJyU) on how to do this with an older build of yours so I have a rough idea what I am doing. My only real question is how to make the machine raise/lower the Z at each point without having a button on-screen? Could Pronterface/S3D control be used instead?

**Comment by andrivet** [comment] 2020-03-22 12:17
Why not using a BLTouch? It is far superior and well supported by ADVi3++.

**Comment by jallen810** [comment] 2020-03-22 14:20
Because BLtouch are expensive and finicky at best, probing works fine on my other machines and is free.

**Comment by andrivet** [comment] 2020-03-22 16:01
https://community.advi3pp.com/t/manual-mesh-bed-leveling/

**Comment by andrivet** [comment] 2020-07-30 20:37
Looks mostly like a duplicate of #59.
Regarding "option to customize the number of points to probe in the X & Y", I will not implement this. Should be done at compile time. Too hacky to do this at runtime time.

**Closed as completed by andrivet** 2020-07-30 20:37 UTC
Labels: enhancement
