### ISSUE TITLE
[Bug] Screen errors in filament loading screen

### ISSUE THREAD

**Issue by tobashadow** [andrivet/ADVi3pp#109] opened 2018-04-29 04:14 UTC
When you try to load filament the screen asks you to select the temp needed with a default of 200c, when you start the process the 200c figure is still in the background.

![20180426_030008](https://user-images.githubusercontent.com/1169228/39403172-fc17ba2e-4b41-11e8-8d88-7f2599b30c9c.jpg)

![20180426_025929](https://user-images.githubusercontent.com/1169228/39403174-0c445894-4b42-11e8-81db-7fdb6b35fd98.jpg)
![20180426_025948](https://user-images.githubusercontent.com/1169228/39403176-12e043b6-4b42-11e8-943f-9aa8d5888e36.jpg)

**Comment by andrivet** [comment] 2018-04-29 10:38
Duplicate of #91

**Closed as completed by andrivet** 2018-04-29 10:38 UTC
Labels: duplicate
