### ISSUE TITLE
Will not x-home if you cancel a print and then restart

### ISSUE THREAD

**Issue by rippledabs** [andrivet/ADVi3pp#15] opened 2017-11-11 00:28 UTC
### Bug Report
- Description: If you cancel a print and then restart it. It will not x-home. 
- Expected behaviour: x-home
- Actual behaviour: It just uses the current position as the x-home for the next print. 
- Steps to reproduce:
  - Cancel a print
  - Restart the print

**Comment by andrivet** [comment] 2017-11-19 18:15
I am able to reproduce this bug in the case of a print from the SD card. Is it correct or do you also see this bug during an USB print?

**Comment by andrivet** [comment] 2017-12-09 13:56
From my latest tests, the bug is still there (USB print)

**Comment by Arsoth** [comment] 2018-01-02 03:43
I can confirm this bug is still occurring on 2.0.1 through USB (at least when using Cura 3.1.0 to print).

**Comment by TTVert** [comment] 2018-02-12 19:03
FYI, this occurred for me w/ stock firmware using repetier host as well.

Dave

**Comment by TTVert** [comment] 2018-02-24 18:12
Curious if this will be something that can be resolved?  This also occurs if you queue up a job in repetier-host before printer is on.  It will start right where the printhead was last left.  It does home Z however.

**Comment by andrivet** [comment] 2018-02-24 19:16
The fix is planned for version 3.0.0

**Comment by TTVert** [comment] 2018-02-24 19:25
I see you had screenshots of screen brightness, how close is 3.0?

**Comment by Martin-Dolan** [comment] 2018-04-01 16:25
This is probably the same thing, but I was doing a print in ABS and just laying down the first layer. I realised it was going to turn to crap as the bed wasn't level enough so I stopped the print, went to the bed level menu, started the level option however it seemed that it thought the x axis "0" was the point on the bed where I had pressed stop.

**Comment by TTVert** [comment] 2018-04-01 16:28
Yep exact situation I run into often.  I have to turn printer completely off and manually home w/ G28  Reset doesn't fix for me.

Dave

**Comment by Martin-Dolan** [comment] 2018-04-01 16:34
I did notice after I had turned it off and on, when I went and started the level process again I saw a screen that said something about "waiting for homing to complete" or something like that. It was only there for a few seconds.  I am 99% certain that it did *NOT* do that when I did the level process after aborting a print so that might help narrow it down?  It is skipping that homing process part of the code when a print has been aborted.

(and I was printing from SD card - I see you asked that of someone else)

**Comment by TTVert** [comment] 2018-04-01 17:12
It's an issue w/ the marlin FW.  Stock also.  andrivet said he was going to resolve it in 3.0.

Dave

**Comment by SureshotM6** [comment] 2018-04-01 23:18
The workaround I have been using so far (which I found on another forum and did not discover myself) is to disable steppers with M18 before homing.  Seems to be working so far, easier than power cycling everything, and is easy enough to put into the generated gcode or octoprint.

**Comment by andrivet** [comment] 2018-04-09 22:21
Is someone able to reproduce this bug is a reproducible way? Is see this but many times, but when I try to reproduce it, I can't...

**Comment by SureshotM6** [comment] 2018-04-09 23:13
> Is someone able to reproduce this bug in a reproducible way?

Yes.  A M17 alone should trigger it (at least on my printer).  For example, run the following after moving the extruder somewhere in the middle of the bed where the homing issue is more easily visible:

```
M17 ; enable all steppers including the extruder
G28 X ; Try to home X.  Won't work
```

I did some measurements and it appears to be a hardware issue.  I've been using this code I wrote as a fix: 5da26d65 "i3plus: fix X homing when extruder is enabled."  There are more details in the commit message, but basically, there is noise from the extruder stepper on the X_MIN pin that is causing the AVR to detect the limit switch as closed when it is actually open.  Feel free to cherry pick that if you agree with the fix.

**Comment by andrivet** [comment] 2018-04-10 17:58
@SureshotM6 I confirm that M17 / G28 X does exhibit the problem. I will try to see the signals with an oscilloscope

**Comment by andrivet** [comment] 2018-04-11 14:53
Fixed in Beta 3

**Closed as completed by andrivet** 2018-04-11 14:53 UTC
Labels: bug

**Comment by TTVert** [comment] 2018-04-11 15:45
Do you have a beta tester area for your FW?   I know you said 3.0 was near and some functionality of it I can use.

Dave

**Comment by andrivet** [comment] 2018-04-12 18:17
@TTVert Sorry, I don't understand what you are asking.

**Comment by andrivet** [comment] 2018-04-13 10:04
Yes of course I need beta testers.

**Comment by ninjanickk** [comment] 2018-04-27 19:38
any idea when beta 3 will be out. i have the issue with my x axis always being triggered and im really hoping beta 3 will help. thank you for your hard work.

**Comment by TTVert** [comment] 2018-04-28 01:04
Why are you deleting our comments?

**Comment by andrivet** [comment] 2018-04-28 08:33
Because this is not the right place to ask for support. For support, please ask your question on Facebook group or on Patreon. I try to keep comments on issues "clean", i.e. with only (technical) information about the issues. So I will also delete this comment.

**Comment by Mechotronic** [comment] 2018-07-11 22:04
Just wanted to say thanks for this! I wonder if a stronger pullup would fix this on the daughter board?
