### ISSUE TITLE
After leveling using the BLTouch sensor, the measured levels are shown in wrong order

### ISSUE THREAD

**Issue by rednaxLamington** [andrivet/ADVi3pp#127] opened 2018-05-31 14:30 UTC
When you perform leveling using a BLTouch sensor, the measured levels at the display are shown in the wrong order.

As stated on the display, the X-axis goes from left to right, the Y axis goes to bottom to top.
But the levels shown on the display, goes on the Y axis from left to right and on the X axis from bottom to top.

In the file advi3pp.cpp, on line 2222 the following code is wrong:
```
void Printer_::sensor_grid_show()
{
#ifdef ADVi3PP_BLTOUCH
    WriteRamDataRequest frame{Variable::Value0};
    for(auto x = 0; x < GRID_MAX_POINTS_X; x++)
       for(auto y = 0; y < GRID_MAX_POINTS_Y; y++)
          frame << Uint16(static_cast<int16_t>(z_values[x][y] * 1000));
    frame.send();

    pages_.show_page(Page::SensorGrid, false);
#endif
}
```
To fix this, the x and y loop has to be reversed:
```
void Printer_::sensor_grid_show()
{
#ifdef ADVi3PP_BLTOUCH
    WriteRamDataRequest frame{Variable::Value0};
    for(auto y = 0; y < GRID_MAX_POINTS_Y; y++)          <--- First do the Y loop
       for(auto x = 0; x < GRID_MAX_POINTS_X; x++)  <-- Nest the X loop
          frame << Uint16(static_cast<int16_t>(z_values[x][y] * 1000));
    frame.send();

    pages_.show_page(Page::SensorGrid, false);
#endif
}
```
I used version 3.0.0 beta 3.
The printer I have is a Wanhao i3 Plus.

I hope this will help.

**Comment by andrivet** [comment] 2018-05-31 14:34
Duplicate of #117.

**Closed as completed by andrivet** 2018-05-31 14:34 UTC
